config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  
	resources :posts
	resources :projects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	extend FriendlyId
  	friendly_id :title, use: :slugged
end

app/models/project.rb
class Project < ApplicationRecord
	extend FriendlyId
  	friendly_id :title, use: :slugged
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit,:update, :destroy ]
	def index
		@post = Post.all.order('created_at desc').paginate(page: params[:page], per_page: 2)
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new post_params

		if @post.save
			redirect_to @post, notice: "Hellz yeah, Talaat! Your article was sucessfully saved! "
		else
			render 'new', notice: "Oh no, Talaat! I was unable to save your post "
		end
	end

	def show
	end

	def edit
		
	end

	def update
		if @post.update post_params
			redirect_to @post, notice: "Hellz yeah, Talaat! Your article was sucessfully updated! "
		else
			render 'edit',notice: "Oh no, Talaat! I was unable to update your post "
		end
	end

	def destroy
		@post.destroy

		redirect_to posts_path
		
	end


	private

	def post_params
		params.require(:post).permit(:title, :content, :slug)	
	end

	def find_post
		@post = Post.friendly.find(params[:id])
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :find_project, only: [:show, :edit, :update, :destroy]

	def index
		@projects = Project.all.order("created_at desc")
		
	end
	def new
		@project = Project.new 
	end
	def create
		@project = Project.new project_params
		if @project.save
			redirect_to @project, notice: "Nice Talaat! That was sucessfully saved!"
		
		else
			render 'new '	
		end
		
	end

	def show
		
	end

	def update
		if @project.update project_params
			redirect_to @project, notice: "Nice Talaat! That was sucessfully updated!"
		else
			render 'edit'
			
		end
	end

	def edit
	end
	def destroy
		@project.destroy
		redirect_to projects_path
		
	end

	private
	def find_project
		@project = Project.friendly.find(params[:id])	
	end
	def project_params
		params.require(:project).permit(:title,:description, :link, :slug)
		
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@posts = Post.all.limit(3).order("created_at desc")
  	@projects = Project.all.limit(3).order("created_at desc")

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	class HTMLwithPygments < Redcarpet::Render::HTML
	    def block_code(code, language)
	      Pygments.highlight(code, lexer: language)
	    end
	end

	def markdown(content)
		renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
		options = {
			autolink: true,
			no_intra_emphasis: true,
			disable_indented_code_blocks: true,
			fenced_code_blocks: true,
			lax_html_blocks: true,
			strikethrough: true,
			superscript: true
		}
		Redcarpet::Markdown.new(renderer, options).render(content).html_safe
	end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

   	<title>Talaat Magdy - Part Developer, Part Student</title>
	<link href="//fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">


    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<header id="main_navigation" class="clearfix">
      <%= link_to "Talaat Magdy", root_path, class: "name" %>
		<nav>
			<%= link_to "Articles", posts_path %>
      <%= link_to "Projects", projects_path %>
			<a href="contact.html">Contact</a>
		</nav>
	</header>

  
  <%= yield %>



    <footer id="main_footer">
      <p class="copyright">&copy; 2018 Talaat Magdy</p>
      <nav>
        <a href="https://twitter.com" target="_blank"><i class="fa fa-twitter"></i></a>
        <a href="https://facebook.com" target="_blank"><i class="fa fa-facebook"></i></a>
        <a href="https://github.com" target="_blank"><i class="fa fa-github"></i></a>
      </nav>
    </footer> 


  </body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
     */
    
    var disqus_config = function () {
        this.page.url = '<%= url_for([@post , {only_path: false}]) %>';  // Replace PAGE_URL with your page's canonical URL variable

        this.page.identifier = '<%= @post.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
        this.page.title = '<%= @post.title%>';

    };
    
    (function() {  // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        
        s.src = 'https://myblogv.disqus.com/embed.js';
        
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<h2> <%= pluralize(@post.errors.count , "error") %> prevented this post from saving:</h2>
		<ul>
			<% @post.errors.full_message.each do |msg| %>
			<li> <%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<%= f.label :title %><br>
	<%= f.text_field :title %>

	<br>
	<br>

	<%= f.label :content , "Write your Article here" %><br>
	<%= f.text_area :content %>
<br><br>

<!--<%= select_date Date.today, prefix: :start_date %> -->

	<br>
	<br>
	
	<%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
	<h1 id="page_title">Stuff I've Written</h1>
	
	<div id="posts_wrapper" class="skinny_wrapper ">
		<% @post.each do |post| %>

		<div class="post">
			<p class="daata"><%= post.created_at.strftime('%A, %B %d')%></p>
			<h2><a href="#"><%= link_to post.title, post %></a></h2>
			<hr>
		</div>
		<% end %>
	</div>

<%= will_paginate @post %>

app/views/posts/new.html.erb
<h1>new Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
	<header>
		<p class="date"><%= @post.created_at.strftime('%A, %B %d') %></p>
		<h1><%= @post.title %></h1>
		<hr>
	</header>

	<div id="content">
		<%= markdown @post.content %>
	</div>

	<hr>

	<div id="share_box">
		<p>Share The DO List</p>
		<!-- Twitter -->
    <a onclick="javascript:window.open('http://twitter.com/share?text=<%= @post.title %> by @talaatmagdyx - &amp;url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-twitter"></i></a>
    <!-- Facebook -->
    <a onclick="javascript:window.open('http://www.facebook.com/sharer.php?u=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);">
    	<i class="fa fa-facebook"></i></a>
    <!-- Google Plus -->
    <a onclick="javascript:window.open('https://plus.google.com/share?url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-google-plus"></i></a>
	</div>

	<hr>

	<%= render 'disqus' %>

</div>

<%= link_to("Edit", edit_post_path(@post) ) %>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
	<% if @project.errors.any? %>
		<h2> <%= pluralize(@project.errors.count , "error") %> prevented this project from saving:</h2>
		<ul>
			<% @project.errors.full_message.each do |msg| %>
			<li> <%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<%= f.label :title %><br>
	<%= f.text_field :title %>

	<br>
	<br>

	<%= f.label :description  %><br>
	<%= f.text_area :description %>
	<br>
	<br>

	<%= f.label :link  %><br>
	<%= f.text_field :link %>
	<br>
	<br>

	<br>
	<br>
	
	<%= f.submit %>

<% end %>

app/views/projects/edit.html.erb
<div class="skinny_wrapper wrapper_paddin">
	<h1>Edit Project</h1>
	<%= render 'form' %>

	

</div>

app/views/projects/index.html.erb
	<h1 id="page_title">Stuff I've built</h1>
	
	<div id="posts_wrapper" class="skinny_wrapper ">
		<% @projects.each do |project| %>

		<div class="post">
			<p class="daata"><%= project.created_at.strftime('%A, %B %d')%></p>
			<h2><a href="#"><%= link_to project.title, project %></a></h2>
			<hr>
		</div>
		<% end %>
	</div>

app/views/projects/new.html.erb
<div class="skinny_wrapper wrapper_paddin">
	<h1>New Project</h1>
	<%= render 'form' %>

</div>

app/views/projects/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
	<header>
		<p class="date"><%= @project.created_at.strftime('%A, %B %d') %></p>
		<h1><%= @project.title %></h1>
		<hr>
	</header>

	<div id="content">
		<%= markdown @project.description %>
	</div>
	
	<hr>

	<div class="button_wrapper">
	<a href="<%= @project.link %>" class="project_button" target="_blank"> Visit <%= @project.title %> </a>
</div>
	<hr>

	<%= link_to "Edit", edit_project_path(@project) %>
	<%= link_to "Delete", project_path(@project), method: :delete, date: {confirm: "Are you sure?"}  %>
</div>

app/views/welcome/index.html.erb
<div class="wrapper wrapper_padding clearfix">
	<div class="col-1 about homepage_content">
		<h2>About</h2>
		<hr>
		<p>I'm a Mobile &amp;  Web developer living in Cairo, EGYPT.</p>
	<p>By day I work as a Full Stack dev / Student at Faculty of Computer and information Science, by night I learn some tricks &amp; code rails applications at <a href="#"> My Work</a></p>
	<p>You can find me speaking in 140 characters on Twitter, and sharing some code on Github.</p>
	</div>
	<div class="col-2 homepage_content">
		<h2>Stuff I've Written</h2>
		<hr>

		<% @posts.each do |post| %>
			<h3><a href="#"> <%= link_to post.title, post %> </a></h3>
			<p class="data"> <%= post.created_at.strftime("%A,%b %d") %> </p>
		<% end %>
	
	</div>



	<div class="col-3 homepage_content">
		<h2>Stuff I've built</h2>
		<hr>
		<% @projects.each do |project| %>
			<h3><a href="#"> <%= link_to project.title, project %> </a></h3>
			<p class="data"> <%= project.created_at.strftime("%A,%b %d") %> </p>
		<% end %>
	</div>
</div>